name: pip install tester

on:
  push:
    branches: ['pip_install_tester']
  # TODO Replace the workflow_dispatch to schedule
  # schedule:
  #   # - cron: '0 16 16 * *'
  #   - cron: '0 16 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        hatchet-version: [1.2.0, 1.3.0, 1.3.1a0]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{format('releases/v{0}', matrix.hatchet-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build unit test dependencies
      run: |
        python -m pip install --upgrade pip pytest

    - name: Build optional dependencies for HDF
      if: ${{ matrix.hatchet-version >= 1.3.1}}
      run: |
        python -m pip install tables

    - name: Install Hatchet
      env:
        HATCHET_VERSION: ${{ matrix.hatchet-version }}
      run: |
        # TODO Change the package from "hatchet" to "llnl-hatchet"
        python -m pip install hatchet==$HATCHET_VERSION

    - name: Test Hatchet
      run: |
        pytest -vv .
